<?php
/**
 *
 * @package phpBB Extension - Add User
 * @author RMcGirr83  (Rich McGirr) rmcgirr83@rmcgirr83.org
 * @copyright (c) 2014 phpbbmodders.net
 * @license GNU General Public License, version 2 (GPL-2.0)
 * @translated into German by Samyonair (http://www.wowfriends.de)
 *
 */

/**
* @ignore
*/
if (!defined('IN_PHPBB'))
{
	exit;
}

/**
* DO NOT CHANGE
*/
if (empty($lang) || !is_array($lang))
{
	$lang = array();
}

// DEVELOPERS PLEASE NOTE
//
// All language files should use UTF-8 as their encoding and the files must not contain a BOM.
//
// Placeholders can now contain order information, e.g. instead of
// 'Page %s of %s' you can (and should) write 'Page %1$s of %2$s', this allows
// translators to re-order the output of data while ensuring it remains correct
//
// You do not need this where single placeholders are used, e.g. 'Message %d' is fine
// equally where a string contains only two placeholders which are used to wrap text
// in a url you again do not need to specify an order e.g., 'Click %sHERE%s' is fine

$lang = array_merge($lang, array(
	'ACP_ACCOUNT_ADDED'			=> 'Der Benutzer wurde angelegt. Der Benutzer kann sich nun mit den Logindaten, die an die von dir angegebene E-Mailadresse gesendet wurden, einloggen.',
	'ACP_ACCOUNT_INACTIVE'		=> 'Der Benutzer wurde angelegt. Die Foreneinstellungen erfordern, dass der Account durch den Benutzer aktiviert wird.<br /> Es wurde ein Aktivierungscode an die von dir für den Benutzer angegebene E-Mailadresse gesendet.',
	'ACP_ACCOUNT_INACTIVE_ADMIN'=> 'Der Benutzer wurde angelegt. Die Foreneinstellungen erfordern, dass der Account durch einen Administrator aktiviert wird.<br />Eine E-Mail wurde an die Administratoren und den Benutzer gesandt und der Benutzer wird darüber informiert wenn der Account aktiviert wurde.',
	'ACP_ADD_USER'				=> 'ACP Benutzer hinzuf&uuml;gen',
	'ACP_ADMIN_ACTIVATE'		=> 'An email will be dispatched to an Administrator for account activation, alternatively you may check the activate account box below to activate the account instantly once created. The user will receive an email containing account login details.',
	'ACP_EMAIL_ACTIVATE'		=> 'Once the account has been created, the user will receive an email containing an activation link to activate the account.',
	'ACP_INSTANT_ACTIVATE'		=> 'The Account will be activated instantly. The user will receive an email with account login details.',

	'ADD_USER'					=> 'Benutzer hinzuf&uuml;gen',
	'ADD_USER_EXPLAIN'			=> 'Create a new user account. If your %sactivation settings%s are to Admin Activativation only, you will have the option to activate the user instantly.',
	'MOD_VERSION'				=> 'Version %s',
	'ADMIN_ACTIVATE'			=> 'Benutzer sofort aktivieren',
	'CONFIRM_PASSWORD'			=> 'Passwort best&aumltigen;',
	'EDIT_USER_GROUPS'			=> '%sClick here to edit the usergroups for this user%s',
	'GROUP_ADD'					=> 'Making a selection here will add the user to the group selected as well as to the registered users group',

	'CONTINUE_EDIT_USER'		=> '%1$sClick here to manage %2$s’s profile%3$s', // e.g.: Click here to edit Joe’s profile.
	'PASSWORD'					=> 'Passwort',
	'PASSWORD_EXPLAIN'			=> 'If you enter a password here, one will not be autogenerated.',
));
